server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Cache immutable assets aggressively
  location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|webp|woff2?)$ {
    expires 5m;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  # SPA fallback (vue-router)
  location / {
    try_files $uri $uri/ /index.html;
  }
}
