apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - crds/coffeeconfigs.yaml
  - crds/quizsessions.yaml
  - crds/quizsubmissions.yaml
  - quiz-rbac.yaml
  - auth-service-rbac.yaml
  - app.yaml
  - examples/coffeeconfig-testnet.yaml
  - examples/quizsession-kubecon-2026.yaml
  - examples/quizsubmission-kubecon-2026.yaml
  - ingress-auth.yaml
  - ingress-frontend.yaml
  - ingress-kubeapi.yaml
