apiVersion: v1
kind: ServiceAccount
metadata:
  name: quiz-access
  namespace: voter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quiz-access
  namespace: voter
rules:
  - apiGroups:
      - examples.configbutler.ai
    resources:
      - quizsessions
      - quizsubmissions
    verbs:
      - get
      - list
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quiz-access
  namespace: voter
subjects:
  - kind: ServiceAccount
    name: quiz-access
    namespace: voter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quiz-access


# You can the token then with 'kubectl -n voter create token quiz-access'
# These tokens are long lived and not advised anymore: already implemented the short lived version now.
